### ISSUE TITLE
The footer isn't positioned properly

### ISSUE THREAD

**Issue by shubheksha** [captainbrosset/devtools-bug-finder#23]
The footer doesn't appear at the bottom of the page. Instead, it float in the middle, obstructing something in the middle. On hovering, the link to the repo vanishes. 
![image](https://cloud.githubusercontent.com/assets/7693422/17821453/60bd4912-666f-11e6-9f60-2a9779f9e977.png)

**Comment by nt1m** [comment]
Thanks for reporting! I'll grab a look

**Comment by captainbrosset** [comment]
Ah, thanks. This probably comes from the layout changes I did back in May, where I did rather big flexbox changes to the layout, and probably only tested properly on Firefox 😞

**Comment by nt1m** [comment]
Fixed by #24
