### ISSUE TITLE
Append query parameter to URL when interacting with UI

### ISSUE THREAD

**Issue by nchevobbe** [captainbrosset/devtools-bug-finder#30]
Since https://github.com/captainbrosset/devtools-bug-finder/pull/28 is now merged, it would be nice if checking a checkbox or a radio append the corresponding queryParam to the URL.

Because parameters can be hard to remember, and if we have that we could just select the wanted tool/options to hand a link to a new contributor for example.

**Comment by captainbrosset** [comment]
Yes! Thanks for filing.
