### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by jryans** [captainbrosset/devtools-bug-finder#32]
Maybe it's worth adding HTTPS support for the site? Mostly I just considered a good idea for any site these days.

It's a bit tricky when deployed to a CNAME from GitHub, though, since there's no web server you control for using Let's Encrypt. I think you'd have to use something like CloudFlare (that's what I use for my personal blog that's served from GitHub).

**Comment by nchevobbe** [comment]
I'm using cloudflare + let's encrypt with github pages too, not too hard to set up

**Comment by aditimaurya** [comment]
Hello @jryans  Can I work on this issue?

**Comment by nt1m** [comment]
Pretty sure this is already HTTPS at this point. See: https://bugs.firefox-dev.tools/?easy&tool=all 

Can someone close this? /cc @nchevobbe maybe?

**Comment by aditimaurya** [comment]
Oh, true that!! Thanks for informing.
